services:
  - type: web
    name: url-shortener
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/spring-boot-url-shortener-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: APP_BASE_URL
        value: https://url-shortener-spring.onrender.com
    plan: free

databases:
  - name: url-shortener-db
    databaseName: urlshortener
    user: postgres
    plan: free